### ISSUE TITLE
Code to auto-open lightshot if closed

### ISSUE THREAD

**Issue by sgtcoder** [burianvlastimil/lightshot-print-screen-linux-handler#1]
Wow, this is a really quick script that works for me. I noticed that it doesn't open Lightshot if for whatever it opens. So if you put this (and you change the path to open the Lightshot, for me, I use PlayOnLinux), it will autoopen before taking a screenshot.

Add after this line:

`lightshot_process_id=$(pgrep "$lightshot_process_name")`

```
if [ -z "$lightshot_process_id" ]; then
    /usr/share/playonlinux/playonlinux --run "Lightshot" %F
    lightshot_process_id=$(pgrep "$lightshot_process_name")
fi
```

**Comment by burianvlastimil** [comment]
Your code has an issue:

Suppose only 10% users actually use PlayOnLinux, and the others use various versions of Wine instead. Then, it would ruin the script. I think the best is not to presume anything.

So, I think it will be best not to add any kind of startup line(s) for Lightshot. And let the users have their Lightshot installed whatever way.

Thank you for an idea anyways.

**Comment by Querulous** [comment]
Path to Lightshot could be provided by environment variable. In that case user could set it once in .bashrc and leave it forever. In case when environment variable would be unset you could simply disable this functionality.

**Comment by burianvlastimil** [comment]
I was thinking a lot about this issue (enhancement). Unfortunately, my final opinion is that the user can and will just edit this little script. Thus, I decided not to implement any auto-startup sequences.
