### ISSUE TITLE
error on my arch system

### ISSUE THREAD

**Issue by plus9a** [burianvlastimil/lightshot-print-screen-linux-handler#2]
./lightshot_print_screen
Error occurred
Error heading: is_integer $(get_process_id Lightshot.exe)
Error message: Lightshot process is not running / get_process_id returned an empty value.

**Comment by burianvlastimil** [comment]
Hey,

my script is looking for the process with `pgrep`, more exactly with a command like this:

```
pgrep "Lightshot.exe" | head -1
```

Could you run this command in your terminal to verify it returns an empty (no) result, please?

More importantly, is Lightshot running when you run the script?

**Comment by burianvlastimil** [comment]
Closing this ticket for the OP's inactivity.
